import {ProjectDataAlias} from "../interfaces/data.interface";
import {SKILL_TITLE} from "../enums/data.enum";

export const DATA_PROJECTS: ProjectDataAlias = {
  NAVAL_GROUP: {
    title: 'Naval Group',
    subtitle: `Développement d'une application de simulation de théâtre de guerre
    pour la formation des officiers de la Marine Nationale de Naval Group.`,
    startDate: '2022-07-01',
    endDate: '2017-11-31',
    happiness: 100,
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.DART_SASS,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.ANGULAR_MATERIAL,
      SKILL_TITLE.STORYBOOK,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.AGILE,
    ],
  },
  MAJORDOC: {
    title: 'Majordoc',
    subtitle: `Développement d'une application de gestion de documents pour
    les entreprises Alstom et POMA.`,
    startDate: '2022-05-15',
    endDate: '2022-06-30',
    happiness: 80,
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.DART_SASS,
      SKILL_TITLE.ANGULAR_MATERIAL,
      SKILL_TITLE.STORYBOOK,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.AGILE,
    ],
  },
  CLICK_UP_MIGRATION: {
    title: 'Migration de Wrike vers ClickUp',
    subtitle: `Création d'un script en Node Js pour la migration des
    données de l'entreprise de Wrike vers ClickUp.`,
    startDate: '2022-04-20',
    endDate: '2022-05-15',
    happiness: 90,
    skills: [
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.CLICK_UP,
      SKILL_TITLE.WRIKE,
    ],
  },
  SOLIVE: {
    title: 'SoLive',
    subtitle: `Développement d'une application de gestion d'écosystèmes informatiques.`,
    startDate: '2022-04-01',
    endDate: '2022-05-15',
    happiness: 90,
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.TECHNICAL_ENGLISH
    ]
  },
  VAL_ARLY: {
    title: 'Site de Val d\'Arly',
    subtitle: `Développement d'un site web pour la station de ski de Val d'Arly.`,
    startDate: '2021-12-01',
    endDate: '2022-03-31',
    happiness: 95,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  MEET_IN_HAINAUT: {
    title: 'Site de Meet in Hainaut',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Hainaut.`,
    startDate: '2021-10-01',
    endDate: '2021-11-30',
    happiness: 65,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  VILLARD_DE_LANS: {
    title: 'Site de Villard de Lans',
    subtitle: `Développement d'un site web pour la station de ski de Villard de Lans.`,
    startDate: '2021-07-01',
    endDate: '2021-09-30',
    happiness: 75,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  ANGERS_DESTINATION: {
    title: 'Site d\'Angers Destination',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Angers.`,
    startDate: '2021-05-01',
    endDate: '2021-06-30',
    happiness: 65,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  ANGERS_EVENT: {
    title: 'Site d\'Angers Événementiel',
    subtitle: `Développement d'un site web pour la promotion des événements à Angers.`,
    startDate: '2021-03-01',
    endDate: '2021-04-30',
    happiness: 60,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  VALLESPIR: {
    title: 'Site de Vallespir',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Vallespir.`,
    startDate: '2021-01-01',
    endDate: '2021-02-28',
    happiness: 90,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  LEUCATE: {
    title: 'Site de Leucate',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Leucate.`,
    startDate: '2020-08-01',
    endDate: '2020-12-31',
    happiness: 75,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  SALON_DE_PROVENCE: {
    title: 'Site de Salon de Provence',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Salon de Provence.`,
    startDate: '2020-03-01',
    endDate: '2020-07-31',
    happiness: 70,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  LES_2_ALPES: {
    title: 'Site des 2 Alpes',
    subtitle: `Développement d'un site web pour la station de ski des 2 Alpes.`,
    startDate: '2019-06-30',
    endDate: '2020-02-28',
    happiness: 100,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  SKI_PLAN: {
    title: 'Ski Plan',
    subtitle: `Développement d'une application web pour afficher les ouvertures et remontées des pistes de ski.`,
    startDate: '2019-01-01',
    endDate: '2019-06-30',
    happiness: 95,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  },
  DORDOGNE_PERIGORD: {
    title: 'Site de Dordogne Périgord',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Dordogne Périgord.`,
    startDate: '2018-09-01',
    endDate: '2018-12-31',
    happiness: 90,
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GIT,
    ],
  }
}
