import {WorkDataInterface} from "../interfaces/data.interface";
import {SKILL_TITLE} from "../enums/data.enum";


export const DATA_WORK: WorkDataInterface[] = [
  {
    title: 'Animateur 2D / 3D',
    subtitle: `Dessin d'animation 2D et 3D`,
    startDate: '2008-06-01',
    endDate: '2009-12-31',
    location: 'Angoulême, France',
    company: '2D 3D Animations',
    happiness: 60,
    skills: [
      SKILL_TITLE.FLASH,
      SKILL_TITLE.MAYA3D,
      SKILL_TITLE.DRAWING,
      SKILL_TITLE.WINDOWS
    ],
  },
  {
    title: 'Animateur 2D',
    subtitle: `Dessin d'animation`,
    startDate: '2010-06-01',
    endDate: '2011-12-31',
    location: 'Angoulême, France',
    company: 'TTK Caribara',
    happiness: 75,
    skills: [
      SKILL_TITLE.FLASH,
      SKILL_TITLE.TOON_BOOM_HARMONY,
      SKILL_TITLE.AFTER_EFFECTS,
      SKILL_TITLE.DRAWING,
      SKILL_TITLE.WINDOWS
    ],
  },
  {
    title: 'Animateur 2D',
    subtitle: `Dessin d'animation`,
    startDate: '2012-01-01',
    endDate: '2013-03-31',
    location: 'Angoulême, France',
    company: 'Once Upon a Toon',
    happiness: 65,
    skills: [
      SKILL_TITLE.FLASH,
      SKILL_TITLE.TOON_BOOM_HARMONY,
      SKILL_TITLE.MAYA3D,
      SKILL_TITLE.DRAWING,
      SKILL_TITLE.WINDOWS
    ],
  },
  {
    title: 'Infographiste',
    subtitle: `Conception d'eMailings, communication interne, affiches,
    flyers, dépliants, plaquettes, cartes de visite, logos, etc.`,
    startDate: '2013-07-01',
    endDate: '2014-08-31',
    location: 'Angoulême, France',
    company: 'SoLocal Group',
    happiness: 92,
    skills: [
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
      SKILL_TITLE.INDESIGN,
      SKILL_TITLE.XD,
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.WINDOWS
    ],
  },
  {
    title: 'Webdesigner',
    subtitle: `Conception de sites web, applications web internes, eMailings`,
    startDate: '2014-11-01',
    endDate: '2016-11-30',
    location: 'Angoulême, France',
    company: 'SoLocal Group',
    happiness: 75,
    skills: [
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.BRACKETS,
      SKILL_TITLE.SUBLIME_TEXT,
      SKILL_TITLE.WINDOWS
      ],
  },
  {
    title: 'Développeur Front-End',
    subtitle: `Conception de site web, eMailings, intégration de contenus, maintenance,
    évolutions des technologies, développement de CRM`,
    startDate: '2016-12-01',
    endDate: '2017-07-31',
    location: 'Bordeaux, France',
    company: 'Netinvestissement',
    happiness: 20,
    skills: [
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.SUBLIME_TEXT,
      SKILL_TITLE.PHP,
      SKILL_TITLE.ZEND,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GULP,
      SKILL_TITLE.BOOTSTRAP,
      SKILL_TITLE.WINDOWS
    ],
  },
  {
    title: 'Développeur Web Full Stack',
    subtitle: `Développement web et de plugins WordPress. - Création Vidéo et musicale`,
    startDate: '2017-08-01',
    endDate: '2018-08-31',
    location: 'Bordeaux, France',
    company: 'Freelance - Auto-entrepreneur',
    happiness: 85,
    skills: [
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GULP,
      SKILL_TITLE.WEBPACK,
      SKILL_TITLE.CUBASE,
      SKILL_TITLE.PREMIERE_PRO,
      SKILL_TITLE.AFTER_EFFECTS,
      SKILL_TITLE.AWS,
      SKILL_TITLE.DOCKER,
      SKILL_TITLE.WINDOWS,
      SKILL_TITLE.SLACK,
      SKILL_TITLE.TECHNICAL_ENGLISH
    ],
  },
  {
    title: 'Développeur Web Full Stack',
    subtitle: `Développement de sites internet pour des destinations touristiques`,
    startDate: '2018-09-01',
    endDate: '2022-03-31',
    location: 'La Rochelle, France',
    company: 'Raccourci Agency',
    happiness: 95,
    skills: [
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.PHP,
      SKILL_TITLE.TWIG,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.MYSQL,
      SKILL_TITLE.POSTGRESQL,
      SKILL_TITLE.REDIS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GULP,
      SKILL_TITLE.WEBPACK,
      SKILL_TITLE.DOCKER,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.FOUNDATION,
      SKILL_TITLE.NGINX,
      SKILL_TITLE.APACHE,
      SKILL_TITLE.JENKINS,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.DRUPAL,
      SKILL_TITLE.VISUAL_STUDIO_CODE,
      SKILL_TITLE.TRELLO,
      SKILL_TITLE.CLICK_UP,
      SKILL_TITLE.DISCORD,
      SKILL_TITLE.MAC_OS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.AGILE
    ],
  },
  {
    title: 'Développeur Web Full Stack',
    subtitle: `Développement d'applications web`,
    startDate: '2022-04-01',
    endDate: '2022-11-30',
    location: 'Angoulême, France',
    company: 'Solicis',
    happiness: 82,
    skills: [
      SKILL_TITLE.HTML,
      SKILL_TITLE.CSS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.PHP,
      SKILL_TITLE.DART_SASS,
      SKILL_TITLE.MONGODB,
      SKILL_TITLE.MYSQL,
      SKILL_TITLE.POSTGRESQL,
      SKILL_TITLE.REDIS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.ANGULAR_MATERIAL,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.EXPRESS,
      SKILL_TITLE.STORYBOOK,
      SKILL_TITLE.DOCKER,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.SONARQUBE,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.PHP_STORM,
      SKILL_TITLE.CLICK_UP,
      SKILL_TITLE.WINDOWS,
      SKILL_TITLE.LINUX,
      SKILL_TITLE.WRIKE,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.AGILE
    ],
  }
];
