import {ProjectDataAlias} from "../interfaces/data.interface";
import {SKILL_TITLE, WORK_CATEGORY} from "../enums/data.enum";

const RACCOURCI_WEBSITES_SKILLS: SKILL_TITLE[] = [
  SKILL_TITLE.PHP,
  SKILL_TITLE.TWIG,
  SKILL_TITLE.JAVASCRIPT,
  SKILL_TITLE.SCSS,
  SKILL_TITLE.WORDPRESS,
  SKILL_TITLE.TECHNICAL_ENGLISH,
  SKILL_TITLE.VISUAL_STUDIO_CODE,
  SKILL_TITLE.SYMFONY,
  SKILL_TITLE.MONGODB,
  SKILL_TITLE.GITLAB,
  SKILL_TITLE.GITHUB,
  SKILL_TITLE.GIT,
];

const SOLOCAL_WEBSITES_SKILLS: SKILL_TITLE[] = [
  SKILL_TITLE.HTML,
  SKILL_TITLE.CSS,
  SKILL_TITLE.JAVASCRIPT,
  SKILL_TITLE.JQUERY,
  SKILL_TITLE.SCSS,
  SKILL_TITLE.WORDPRESS,
  SKILL_TITLE.PHOTOSHOP,
];

const SOLOCAL_EMAILING_SKILLS: SKILL_TITLE[] = [
  SKILL_TITLE.HTML,
  SKILL_TITLE.CSS,
  SKILL_TITLE.PHOTOSHOP,
  SKILL_TITLE.ILLUSTRATOR,
];

const SOLOCAL_MAILING_SKILLS: SKILL_TITLE[] = [
  SKILL_TITLE.PHOTOSHOP,
  SKILL_TITLE.ILLUSTRATOR,
];

export const DATA_PROJECTS: ProjectDataAlias = {
  NAVAL_GROUP: {
    title: 'Naval Group',
    subtitle: `Développement d'une application de simulation de théâtre de guerre
    pour la formation des officiers de la Marine Nationale de Naval Group.`,
    startDate: '2022-07-01',
    endDate: '2017-11-31',
    happiness: 100,
    category: [
      WORK_CATEGORY.WEB_APPLICATION
    ],
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.DART_SASS,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.ANGULAR_MATERIAL,
      SKILL_TITLE.STORYBOOK,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.AGILE,
    ],
  },
  MAJORDOC: {
    title: 'Majordoc',
    subtitle: `Développement d'une application de gestion de documents pour
    les entreprises Alstom et POMA.`,
    startDate: '2022-05-15',
    endDate: '2022-06-30',
    happiness: 80,
    category: [
      WORK_CATEGORY.WEB_APPLICATION,
      WORK_CATEGORY.MOBILE_APPLICATION,
    ],
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.DART_SASS,
      SKILL_TITLE.ANGULAR_MATERIAL,
      SKILL_TITLE.STORYBOOK,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.AGILE,
    ],
  },
  CLICK_UP_MIGRATION: {
    title: 'Migration de Wrike vers ClickUp',
    subtitle: `Création d'un script en Node Js pour la migration des
    données de l'entreprise de Wrike vers ClickUp.`,
    startDate: '2022-04-20',
    endDate: '2022-05-15',
    happiness: 90,
    category: [
      WORK_CATEGORY.OTHERS,
    ],
    skills: [
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.TECHNICAL_ENGLISH,
      SKILL_TITLE.WEBSTORM,
      SKILL_TITLE.CLICK_UP,
      SKILL_TITLE.WRIKE,
    ],
  },
  SOLIVE: {
    title: 'SoLive',
    subtitle: `Développement d'une application de gestion d'écosystèmes informatiques.`,
    startDate: '2022-04-01',
    endDate: '2022-05-15',
    happiness: 90,
    category: [
      WORK_CATEGORY.WEB_APPLICATION,
    ],
    skills: [
      SKILL_TITLE.ANGULAR,
      SKILL_TITLE.TYPESCRIPT,
      SKILL_TITLE.RXJS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.NESTJS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.POSTMAN,
      SKILL_TITLE.TECHNICAL_ENGLISH
    ]
  },
  VAL_ARLY: {
    title: 'Site de Val d\'Arly',
    subtitle: `Développement d'un site web pour la station de ski de Val d'Arly.`,
    startDate: '2021-12-01',
    endDate: '2022-03-31',
    happiness: 95,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  MEET_IN_HAINAUT: {
    title: 'Site de Meet in Hainaut',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Hainaut.`,
    startDate: '2021-10-01',
    endDate: '2021-11-30',
    happiness: 65,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  VILLARD_DE_LANS: {
    title: 'Site de Villard de Lans',
    subtitle: `Développement d'un site web pour la station de ski de Villard de Lans.`,
    startDate: '2021-07-01',
    endDate: '2021-09-30',
    happiness: 75,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  ANGERS_DESTINATION: {
    title: 'Site d\'Angers Destination',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Angers.`,
    startDate: '2021-05-01',
    endDate: '2021-06-30',
    happiness: 65,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  ANGERS_EVENT: {
    title: 'Site d\'Angers Événementiel',
    subtitle: `Développement d'un site web pour la promotion des événements à Angers.`,
    startDate: '2021-03-01',
    endDate: '2021-04-30',
    happiness: 60,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  VALLESPIR: {
    title: 'Site de Vallespir',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Vallespir.`,
    startDate: '2021-01-01',
    endDate: '2021-02-28',
    happiness: 90,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  LEUCATE: {
    title: 'Site de Leucate',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Leucate.`,
    startDate: '2020-08-01',
    endDate: '2020-12-31',
    happiness: 75,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  SALON_DE_PROVENCE: {
    title: 'Site de Salon de Provence',
    subtitle: `Développement d'un site web pour la promotion du tourisme à Salon de Provence.`,
    startDate: '2020-03-01',
    endDate: '2020-07-31',
    happiness: 70,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  LES_2_ALPES: {
    title: 'Site des 2 Alpes',
    subtitle: `Développement d'un site web pour la station de ski des 2 Alpes.`,
    startDate: '2019-06-30',
    endDate: '2020-02-28',
    happiness: 100,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  SKI_PLAN: {
    title: 'Ski Plan',
    subtitle: `Développement d'une application web pour afficher les ouvertures et remontées des pistes de ski.`,
    startDate: '2019-01-01',
    endDate: '2019-06-30',
    happiness: 95,
    category: [WORK_CATEGORY.WEB_APPLICATION, WORK_CATEGORY.MOBILE_APPLICATION],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  DORDOGNE_PERIGORD: {
    title: 'Site de Dordogne Périgord',
    subtitle: `Développement d'un site web pour la promotion du tourisme en Dordogne Périgord.`,
    startDate: '2018-09-01',
    endDate: '2018-12-31',
    happiness: 90,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: RACCOURCI_WEBSITES_SKILLS,
  },
  DEVTOOLS: {
    title: 'DevTools',
    subtitle: `Développement d'une application web pour afficher les outils de développement.`,
    startDate: '2020-03-01',
    endDate: '2021-04-30',
    happiness: 100,
    category: [WORK_CATEGORY.WEB_APPLICATION],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.NODE_JS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.GULP,
      SKILL_TITLE.WEBPACK,
      SKILL_TITLE.TECHNICAL_ENGLISH
    ],
  },
  BRASERO_INDUSTRIE: {
    title: 'Site de Brasero Industrie',
    subtitle: `Développement d'un site eCommerce pour la société Brasero Industrie.`,
    startDate: '2018-08-01',
    endDate: '2018-08-31',
    happiness: 75,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WOOCOMMERCE,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
    ],
  },
  MELUSINE: {
    title: 'Site de Melusine',
    subtitle: `Développement d'un site internet pour la société Melusine.`,
    startDate: '2018-07-01',
    endDate: '2018-07-31',
    happiness: 75,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
    ],
  },
  CREAREGLE: {
    title: 'Site de Crearegle',
    subtitle: `Développement d'un site eCommerce pour la société Crearegle.`,
    startDate: '2018-03-01',
    endDate: '2018-06-30',
    happiness: 90,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.WOOCOMMERCE,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
    ],
  },
  SOINS_EQUILIBRE: {
    title: 'Site de Soins d\'Equilibre',
    subtitle: `Développement d'un site internet pour le salon de massage Soins d'Equilibre.`,
    startDate: '2018-02-01',
    endDate: '2018-02-28',
    happiness: 85,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
    ],
  },
  ANYM_LIVE: {
    title: 'Site d\'Anym Live',
    subtitle: `Développement d'un site eCommerce de vente de plugins WordPress`,
    startDate: '2017-12-01',
    endDate: '2018-01-31',
    happiness: 85,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
      SKILL_TITLE.WOOCOMMERCE
    ],
  },
  ANYM_LIVE_EDITOR: {
    title: 'Plugin WordPress Anym Live Editor',
    subtitle: `Développement du plugin WordPress Anym Live Editor, qui est un IDE en ligne
    pour WordPress.`,
    startDate: '2017-05-01',
    endDate: '2018-01-31',
    happiness: 100,
    category: [WORK_CATEGORY.WEB_APPLICATION],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.WEBPACK,
    ],
  },
  XONAO: {
    title: 'Site eCommerce de Xonao',
    subtitle: `Développement d'un site eCommerce pour la société Xonao.`,
    startDate: '2017-07-01',
    endDate: '2017-12-31',
    happiness: 90,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.WORDPRESS,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.ILLUSTRATOR,
      SKILL_TITLE.WOOCOMMERCE
    ],
  },
  WANTED_CREW_CD: {
    title: 'Création du CD Wanted Crew',
    subtitle: `Enregistrement, mixage et mastering du CD Wanted Crew, groupe de reggae français.`,
    startDate: '2017-02-01',
    endDate: '2017-06-31',
    happiness: 100,
    category: [WORK_CATEGORY.MUSIC_PRODUCTION],
    skills: [
      SKILL_TITLE.CUBASE,
      SKILL_TITLE.REAPER,
      SKILL_TITLE.ABLETON_LIVE,
      SKILL_TITLE.MASTERING,
      SKILL_TITLE.MIXING,
      SKILL_TITLE.RECORDING,
      SKILL_TITLE.MUSIC_THEORY,
      SKILL_TITLE.MAO,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.VIOLIN
    ],
  },
  SOLIALMA_CD: {
    title: 'Création du CD Solialma',
    subtitle: `Enregistrement, mixage et mastering du CD Solialma, groupe de Flamenco.`,
    startDate: '2014-02-01',
    endDate: '2014-06-31',
    happiness: 100,
    category: [WORK_CATEGORY.MUSIC_PRODUCTION],
    skills: [
      SKILL_TITLE.CUBASE,
      SKILL_TITLE.REAPER,
      SKILL_TITLE.MASTERING,
      SKILL_TITLE.MIXING,
      SKILL_TITLE.RECORDING,
      SKILL_TITLE.MUSIC_THEORY,
      SKILL_TITLE.MAO,
      SKILL_TITLE.PHOTOSHOP,
      SKILL_TITLE.VIOLIN
    ],
  },
  EXTRANET: {
    title: 'Extranet',
    subtitle: `Développement d'un extranet pour la société NetInvestissement.`,
    startDate: '2017-02-01',
    endDate: '2017-07-31',
    happiness: 100,
    category: [WORK_CATEGORY.WEB_APPLICATION, WORK_CATEGORY.MOBILE_APPLICATION],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.WEBPACK,
    ],
  },
  NETINVESTISSEMENT_WEB: {
    title: 'Site de NetInvestissement',
    subtitle: `Développement d'un site internet pour la société NetInvestissement.`,
    startDate: '2016-12-01',
    endDate: '2017-07-31',
    happiness: 100,
    category: [WORK_CATEGORY.WEBSITE_DEVELOPMENT],
    skills: [
      SKILL_TITLE.PHP,
      SKILL_TITLE.SYMFONY,
      SKILL_TITLE.JAVASCRIPT,
      SKILL_TITLE.ZEND,
      SKILL_TITLE.JQUERY,
      SKILL_TITLE.SCSS,
      SKILL_TITLE.GIT,
      SKILL_TITLE.GITLAB,
      SKILL_TITLE.GITHUB,
      SKILL_TITLE.WEBPACK,
      SKILL_TITLE.BOOTSTRAP,
    ],
  },
  SOLOCAL_SIGNORET: {
    title: 'Site web Signoret',
    subtitle: `Développement d'un site internet pour la société Signoret.`,
    startDate: '2016-11-01',
    endDate: '2016-11-30',
    happiness: 10,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_VERANDA_SICARD: {
    title: 'Site web Veranda Sicard',
    subtitle: `Développement d'un site internet pour la société Veranda Sicard.`,
    startDate: '2016-10-15',
    endDate: '2016-11-15',
    happiness: 20,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ASSB: {
    title: 'Site web ASSB Serrurerie',
    subtitle: `Développement d'un site internet pour la société ASSB Serrurerie.`,
    startDate: '2016-10-01',
    endDate: '2016-10-31',
    happiness: 40,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_MARBRERIE_GILLES: {
    title: 'Site web Marbrerie Gilles',
    subtitle: `Développement d'un site internet pour la société Marbrerie Gilles.`,
    startDate: '2016-09-01',
    endDate: '2016-09-30',
    happiness: 10,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_MARBRERIE_GIRARD: {
    title: 'Site web Marbrerie Girard',
    subtitle: `Développement d'un site internet pour la société Marbrerie Girard.`,
    startDate: '2016-08-01',
    endDate: '2016-08-31',
    happiness: 5,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_MILLE_UN_JARDINS: {
    title: 'Site web Mille et un Jardins',
    subtitle: `Développement d'un site internet pour la société Mille et un Jardins.`,
    startDate: '2016-07-01',
    endDate: '2016-07-31',
    happiness: 40,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_JDS_RENOVATION: {
    title: 'Site web JDS Rénovation',
    subtitle: `Développement d'un site internet pour la société JDS Rénovation.`,
    startDate: '2016-06-01',
    endDate: '2016-06-30',
    happiness: 60,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ETS_FOUCAULT: {
    title: 'Site web ETS Foucault',
    subtitle: `Développement d'un site internet pour la société ETS Foucault.`,
    startDate: '2016-05-01',
    endDate: '2016-05-31',
    happiness: 80,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_DURAND_EROLES_CASTAGNET: {
    title: 'Site web Durand Eroles Castagnet',
    subtitle: `Développement d'un site internet pour la société Durand Eroles Castagnet.`,
    startDate: '2016-04-01',
    endDate: '2016-04-30',
    happiness: 35,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_DONNET: {
    title: 'Site web Donnet',
    subtitle: `Développement d'un site internet pour la société Donnet.`,
    startDate: '2016-03-01',
    endDate: '2016-03-31',
    happiness: 15,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_CORDERIE_CLEMENT: {
    title: 'Site web Corderie Clément',
    subtitle: `Développement d'un site internet pour la société Corderie Clément.`,
    startDate: '2016-02-01',
    endDate: '2016-02-29',
    happiness: 60,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_NICE_WOLFF: {
    title: 'Site web Nice Wolff',
    subtitle: `Développement d'un site internet pour l'avocate Nice Wolff.`,
    startDate: '2016-01-01',
    endDate: '2016-01-31',
    happiness: 55,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ASTRAL: {
    title: 'Site web Astral',
    subtitle: `Développement d'un site internet pour la société Astral.`,
    startDate: '2015-12-01',
    endDate: '2015-12-31',
    happiness: 75,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_APS: {
    title: 'Site web APS',
    subtitle: `Développement d'un site internet pour la société APS.`,
    startDate: '2015-11-01',
    endDate: '2015-11-30',
    happiness: 25,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ANDEOL_FERMETURES: {
    title: 'Site web Andeol Fermétures',
    subtitle: `Développement d'un site internet pour la société Andeol Fermétures.`,
    startDate: '2015-10-01',
    endDate: '2015-10-31',
    happiness: 35,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_CATALANO: {
    title: 'Site web Catalano',
    subtitle: `Développement d'un site internet pour la société Catalano.`,
    startDate: '2015-09-01',
    endDate: '2015-09-30',
    happiness: 15,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_POYET: {
    title: 'Site web Poyet',
    subtitle: `Développement d'un site internet pour la société Poyet.`,
    startDate: '2015-08-01',
    endDate: '2015-08-31',
    happiness: 10,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_MIGEON: {
    title: 'Site web Migeon',
    subtitle: `Développement d'un site internet pour la société Migeon.`,
    startDate: '2015-07-01',
    endDate: '2015-07-31',
    happiness: 12,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_LEHOUX: {
    title: 'Site web Lehoux',
    subtitle: `Développement d'un site internet pour la société Lehoux.`,
    startDate: '2015-06-01',
    endDate: '2015-06-30',
    happiness: 80,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ESCANOR: {
    title: 'Site web Escanor',
    subtitle: `Développement d'un site internet pour la société Escanor.`,
    startDate: '2015-05-01',
    endDate: '2015-05-31',
    happiness: 35,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ABITAL: {
    title: 'Site web Abital',
    subtitle: `Développement d'un site internet pour la société Abital.`,
    startDate: '2015-04-01',
    endDate: '2015-04-30',
    happiness: 65,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_MARATHON: {
    title: 'Site web Marathon',
    subtitle: `Développement d'un site internet pour la société Marathon.`,
    startDate: '2015-03-01',
    endDate: '2015-03-31',
    happiness: 50,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_SEM_ESPACES_VERTS: {
    title: 'Site web SEM Espaces Verts',
    subtitle: `Développement d'un site internet pour la société SEM Espaces Verts.`,
    startDate: '2015-02-01',
    endDate: '2015-02-28',
    happiness: 70,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_AF62: {
    title: 'Site web AF62',
    subtitle: `Développement d'un site internet pour la société AF62.`,
    startDate: '2015-01-01',
    endDate: '2015-01-31',
    happiness: 20,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_SAD_LOC: {
    title: 'Site web SAD Loc',
    subtitle: `Développement d'un site internet pour la société SAD Loc.`,
    startDate: '2014-12-01',
    endDate: '2014-12-31',
    happiness: 40,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ROADY: {
    title: 'Site web Roady',
    subtitle: `Développement d'un site internet pour la société Roady.`,
    startDate: '2014-11-01',
    endDate: '2014-11-30',
    happiness: 45,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_CENA: {
    title: 'Site web Maison CENA',
    subtitle: `Développement d'un site internet pour la société Maison CENA.`,
    startDate: '2014-10-01',
    endDate: '2014-10-31',
    happiness: 60,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ETS_MARTIN: {
    title: 'Site web ETS Martin',
    subtitle: `Développement d'un site internet pour la société ETS Martin.`,
    startDate: '2014-09-01',
    endDate: '2014-09-30',
    happiness: 55,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_ASTORE_FERMETURES: {
    title: 'Site web Astore Fermétures',
    subtitle: `Développement d'un site internet pour la société Astore Fermétures.`,
    startDate: '2014-08-01',
    endDate: '2014-08-31',
    happiness: 70,
    category: [WORK_CATEGORY.WEBSITE_DESIGN],
    skills: SOLOCAL_WEBSITES_SKILLS,
  },
  SOLOCAL_EM_ADHAP: {
    title: 'eMailing Adhap Services',
    subtitle: `Développement d'un eMailing pour la société Adhap Services.`,
    startDate: '2014-08-20',
    endDate: '2014-08-31',
    happiness: 30,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_AFRELEC: {
    title: 'eMailing Afrelec',
    subtitle: `Développement d'un eMailing pour la société Afrelec.`,
    startDate: '2014-08-10',
    endDate: '2014-08-19',
    happiness: 40,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_AMOURDEFLEURS: {
    title: 'eMailing Amour de Fleurs',
    subtitle: `Développement d'un eMailing pour la société Amour de Fleurs.`,
    startDate: '2014-08-01',
    endDate: '2014-08-09',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ARSONNEAU: {
    title: 'eMailing Arsonneau',
    subtitle: `Développement d'un eMailing pour la société Arsonneau.`,
    startDate: '2014-07-20',
    endDate: '2014-07-31',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ATRIUM: {
    title: 'eMailing Atrium',
    subtitle: `Développement d'un eMailing pour la société Atrium.`,
    startDate: '2014-07-10',
    endDate: '2014-07-19',
    happiness: 40,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_AVIVA: {
    title: 'eMailing Aviva',
    subtitle: `Développement d'un eMailing pour la société Aviva.`,
    startDate: '2014-07-01',
    endDate: '2014-07-09',
    happiness: 60,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_AVOCAT_SPECIALISTE: {
    title: 'eMailing Avocat Spécialiste',
    subtitle: `Développement d'un eMailing pour la société Avocat Spécialiste.`,
    startDate: '2014-06-20',
    endDate: '2014-06-30',
    happiness: 30,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_BEAU_SEJOUR: {
    title: 'eMailing Beau Séjour',
    subtitle: `Développement d'un eMailing pour la société Beau Séjour.`,
    startDate: '2014-06-10',
    endDate: '2014-06-19',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_BONES_HORES: {
    title: 'eMailing Bones Hôres',
    subtitle: `Développement d'un eMailing pour la société Bones Hôres.`,
    startDate: '2014-06-01',
    endDate: '2014-06-09',
    happiness: 60,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CANDAS: {
    title: 'eMailing Candas',
    subtitle: `Développement d'un eMailing pour la société Candas.`,
    startDate: '2014-05-20',
    endDate: '2014-05-31',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CERAG: {
    title: 'eMailing Cerag',
    subtitle: `Développement d'un eMailing pour la société Cerag.`,
    startDate: '2014-05-10',
    endDate: '2014-05-19',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CHORALIS: {
    title: 'eMailing Choralis',
    subtitle: `Développement d'un eMailing pour la société Choralis.`,
    startDate: '2014-05-01',
    endDate: '2014-05-09',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CLERMONT_MUSIQUE: {
    title: 'eMailing Clermont Musique',
    subtitle: `Développement d'un eMailing pour la société Clermont Musique.`,
    startDate: '2014-04-20',
    endDate: '2014-04-30',
    happiness: 35,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CLUB_DU_CUIR: {
    title: 'eMailing Club du Cuir',
    subtitle: `Développement d'un eMailing pour la société Club du Cuir.`,
    startDate: '2014-04-10',
    endDate: '2014-04-19',
    happiness: 40,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_COMBLESPACE: {
    title: 'eMailing Comblespace',
    subtitle: `Développement d'un eMailing pour la société Comblespace.`,
    startDate: '2014-04-01',
    endDate: '2014-04-09',
    happiness: 10,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_COMBLEZ_MOI: {
    title: 'eMailing Comblez Moi',
    subtitle: `Développement d'un eMailing pour la société Comblez Moi.`,
    startDate: '2014-03-20',
    endDate: '2014-03-31',
    happiness: 40,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CONSEIL_DECORS: {
    title: 'eMailing Conseil Décors',
    subtitle: `Développement d'un eMailing pour la société Conseil Décors.`,
    startDate: '2014-03-10',
    endDate: '2014-03-19',
    happiness: 3,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CROTZ: {
    title: 'eMailing Crotz',
    subtitle: `Développement d'un eMailing pour la société Crotz.`,
    startDate: '2014-03-01',
    endDate: '2014-03-09',
    happiness: 10,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_CSDESIGN: {
    title: 'eMailing CSDesign',
    subtitle: `Développement d'un eMailing pour la société CSDesign.`,
    startDate: '2014-02-20',
    endDate: '2014-02-28',
    happiness: 20,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ECORIDERS: {
    title: 'eMailing Ecoriders',
    subtitle: `Développement d'un eMailing pour la société Ecoriders.`,
    startDate: '2014-02-10',
    endDate: '2014-02-19',
    happiness: 35,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ESPACE_LIBERTE: {
    title: 'eMailing Espace Liberté',
    subtitle: `Développement d'un eMailing pour la société Espace Liberté.`,
    startDate: '2014-02-01',
    endDate: '2014-02-09',
    happiness: 15,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_GODEFROID: {
    title: 'eMailing Godefroid',
    subtitle: `Développement d'un eMailing pour la société Godefroid.`,
    startDate: '2014-01-20',
    endDate: '2014-01-31',
    happiness: 15,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_IDEAL_MENUISERIE: {
    title: 'eMailing Idéal Menuiserie',
    subtitle: `Développement d'un eMailing pour la société Idéal Menuiserie.`,
    startDate: '2014-01-10',
    endDate: '2014-01-19',
    happiness: 15,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_JEFFERSON: {
    title: 'eMailing Jefferson',
    subtitle: `Développement d'un eMailing pour la société Jefferson.`,
    startDate: '2014-01-01',
    endDate: '2014-01-09',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_KARUKERA: {
    title: 'eMailing Karukera',
    subtitle: `Développement d'un eMailing pour la société Karukera.`,
    startDate: '2013-12-20',
    endDate: '2013-12-31',
    happiness: 55,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_KFORM: {
    title: 'eMailing KForm',
    subtitle: `Développement d'un eMailing pour la société KForm.`,
    startDate: '2013-12-10',
    endDate: '2013-12-19',
    happiness: 80,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_LYON_REMORQUAGE: {
    title: 'eMailing Lyon Remorquage',
    subtitle: `Développement d'un eMailing pour la société Lyon Remorquage.`,
    startDate: '2013-12-01',
    endDate: '2013-12-09',
    happiness: 1,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_MIDIFIOUL: {
    title: 'eMailing Midifioûl',
    subtitle: `Développement d'un eMailing pour la société Midifioûl.`,
    startDate: '2013-11-20',
    endDate: '2013-11-30',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_MISE_EN_BOUCHE: {
    title: 'eMailing Mise en Bouche',
    subtitle: `Développement d'un eMailing pour la société Mise en Bouche.`,
    startDate: '2013-11-10',
    endDate: '2013-11-19',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ORPI: {
    title: 'eMailing Orpi',
    subtitle: `Développement d'un eMailing pour la société Orpi.`,
    startDate: '2013-11-01',
    endDate: '2013-11-09',
    happiness: 5,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_PANORAMIC: {
    title: 'eMailing Panoramic',
    subtitle: `Développement d'un eMailing pour la société Panoramic.`,
    startDate: '2013-10-20',
    endDate: '2013-10-31',
    happiness: 5,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_RAY_ASSAINISSEMENT: {
    title: 'eMailing Ray Assainissement',
    subtitle: `Développement d'un eMailing pour la société Ray Assainissement.`,
    startDate: '2013-10-10',
    endDate: '2013-10-19',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_REPROCOLOR: {
    title: 'eMailing Reprocolor',
    subtitle: `Développement d'un eMailing pour la société Reprocolor.`,
    startDate: '2013-10-01',
    endDate: '2013-10-09',
    happiness: 10,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ROCK_THE_HOUSE: {
    title: 'eMailing Rock the House',
    subtitle: `Développement d'un eMailing pour la société Rock the House.`,
    startDate: '2013-09-20',
    endDate: '2013-09-30',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_SLPRODUCTION: {
    title: 'eMailing SLProduction',
    subtitle: `Développement d'un eMailing pour la société SLProduction.`,
    startDate: '2013-09-10',
    endDate: '2013-09-19',
    happiness: 50,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_SOMAFRAC: {
    title: 'eMailing Somafraç',
    subtitle: `Développement d'un eMailing pour la société Somafraç.`,
    startDate: '2013-09-01',
    endDate: '2013-09-09',
    happiness: 15,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_SOMATRANS: {
    title: 'eMailing Somatrans',
    subtitle: `Développement d'un eMailing pour la société Somatrans.`,
    startDate: '2013-08-20',
    endDate: '2013-08-31',
    happiness: 65,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_STOP_AUTOECOLE: {
    title: 'eMailing Stop Auto-école',
    subtitle: `Développement d'un eMailing pour la société Stop Auto-école.`,
    startDate: '2013-08-10',
    endDate: '2013-08-19',
    happiness: 30,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_TAXIF1: {
    title: 'eMailing TaxiF1',
    subtitle: `Développement d'un eMailing pour la société TaxiF1.`,
    startDate: '2013-08-01',
    endDate: '2013-08-09',
    happiness: 10,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_TRANSALPSERVICES: {
    title: 'eMailing Transalpservices',
    subtitle: `Développement d'un eMailing pour la société Transalpservices.`,
    startDate: '2013-07-20',
    endDate: '2013-07-31',
    happiness: 70,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_TRAVAUX_HERCULES: {
    title: 'eMailing Travaux Hercule',
    subtitle: `Développement d'un eMailing pour la société Travaux Hercule.`,
    startDate: '2013-07-10',
    endDate: '2013-07-19',
    happiness: 45,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_TRISPAGE: {
    title: 'eMailing Trispage',
    subtitle: `Développement d'un eMailing pour la société Trispage.`,
    startDate: '2013-07-01',
    endDate: '2013-07-09',
    happiness: 20,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_VBL: {
    title: 'eMailing VBL',
    subtitle: `Développement d'un eMailing pour la société VBL.`,
    startDate: '2013-06-20',
    endDate: '2013-06-30',
    happiness: 45,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_VERDIERFUSCO: {
    title: 'eMailing Verdier Fusco',
    subtitle: `Développement d'un eMailing pour la société Verdier Fusco.`,
    startDate: '2013-06-10',
    endDate: '2013-06-19',
    happiness: 5,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_VILLA_DE_VINCI: {
    title: 'eMailing Villa de Vinci',
    subtitle: `Développement d'un eMailing pour la société Villa de Vinci.`,
    startDate: '2013-06-01',
    endDate: '2013-06-09',
    happiness: 45,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_VISA_EMPLOI: {
    title: 'eMailing Visa Emploi',
    subtitle: `Développement d'un eMailing pour la société Visa Emploi.`,
    startDate: '2013-05-20',
    endDate: '2013-05-31',
    happiness: 40,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_VOILLARD: {
    title: 'eMailing Voillard',
    subtitle: `Développement d'un eMailing pour la société Voillard.`,
    startDate: '2013-05-10',
    endDate: '2013-05-19',
    happiness: 25,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_EM_ZEROTAXE: {
    title: 'eMailing Zerotaxe',
    subtitle: `Développement d'un eMailing pour la société Zerotaxe.`,
    startDate: '2013-05-01',
    endDate: '2013-05-09',
    happiness: 60,
    category: [WORK_CATEGORY.EMAILING],
    skills: SOLOCAL_EMAILING_SKILLS,
  },
  SOLOCAL_M_ACFWILL: {
    title: 'Mailing papier ACFWILL',
    subtitle: `Développement d'un mailing papier pour la société ACFWILL.`,
    startDate: '2013-04-25',
    endDate: '2013-04-30',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_ALU_CONCEPT: {
    title: 'Mailing papier Alu Concept',
    subtitle: `Développement d'un mailing papier pour la société Alu Concept.`,
    startDate: '2013-04-20',
    endDate: '2013-04-24',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_ASR: {
    title: 'Mailing papier ASR',
    subtitle: `Développement d'un mailing papier pour la société ASR.`,
    startDate: '2013-04-15',
    endDate: '2013-04-19',
    happiness: 65,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_BRAVIN: {
    title: 'Mailing papier Bravin',
    subtitle: `Développement d'un mailing papier pour la société Bravin.`,
    startDate: '2013-04-10',
    endDate: '2013-04-14',
    happiness: 70,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_CIGAMM: {
    title: 'Mailing papier Cigamm',
    subtitle: `Développement d'un mailing papier pour la société Cigamm.`,
    startDate: '2013-04-05',
    endDate: '2013-04-09',
    happiness: 60,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_COMBLESPACE: {
    title: 'Mailing papier Comblespace',
    subtitle: `Développement d'un mailing papier pour la société Comblespace.`,
    startDate: '2013-04-01',
    endDate: '2013-04-04',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_COPYTIME: {
    title: 'Mailing papier Copytime',
    subtitle: `Développement d'un mailing papier pour la société Copytime.`,
    startDate: '2013-03-25',
    endDate: '2013-03-29',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_DOORWELL: {
    title: 'Mailing papier Doorwell',
    subtitle: `Développement d'un mailing papier pour la société Doorwell.`,
    startDate: '2013-03-20',
    endDate: '2013-03-24',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_EDIAC_FORMATION: {
    title: 'Mailing papier Ediac Formation',
    subtitle: `Développement d'un mailing papier pour la société Ediac Formation.`,
    startDate: '2013-03-15',
    endDate: '2013-03-19',
    happiness: 2,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_EMPX: {
    title: 'Mailing papier Empx',
    subtitle: `Développement d'un mailing papier pour la société Empx.`,
    startDate: '2013-03-10',
    endDate: '2013-03-14',
    happiness: 5,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_FLOREVER: {
    title: 'Mailing papier Florever',
    subtitle: `Développement d'un mailing papier pour la société Florever.`,
    startDate: '2013-03-05',
    endDate: '2013-03-09',
    happiness: 80,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_GALERIES_VASSEUR: {
    title: 'Mailing papier Galeries Vasseur',
    subtitle: `Développement d'un mailing papier pour la société Galeries Vasseur.`,
    startDate: '2013-03-01',
    endDate: '2013-03-04',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_GOUEDIC: {
    title: 'Mailing papier Gouedic',
    subtitle: `Développement d'un mailing papier pour la société Gouedic.`,
    startDate: '2013-02-25',
    endDate: '2013-02-28',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_GRANJON: {
    title: 'Mailing papier Granjon',
    subtitle: `Développement d'un mailing papier pour la société Granjon.`,
    startDate: '2013-02-20',
    endDate: '2013-02-24',
    happiness: 55,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_GRIFFOIN: {
    title: 'Mailing papier Griffoin',
    subtitle: `Développement d'un mailing papier pour la société Griffoin.`,
    startDate: '2013-02-15',
    endDate: '2013-02-19',
    happiness: 70,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_INTERMAIDE: {
    title: 'Mailing papier Intermaide',
    subtitle: `Développement d'un mailing papier pour la société Intermaide.`,
    startDate: '2013-02-10',
    endDate: '2013-02-14',
    happiness: 50,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_JARDINS_DU_SOLEIL: {
    title: 'Mailing papier Jardins du Soleil',
    subtitle: `Développement d'un mailing papier pour la société Jardins du Soleil.`,
    startDate: '2013-02-05',
    endDate: '2013-02-09',
    happiness: 40,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_LES_JARDINS_ST_TROPEZ: {
    title: 'Mailing papier Les Jardins St Tropez',
    subtitle: `Développement d'un mailing papier pour la société Les Jardins St Tropez.`,
    startDate: '2013-02-01',
    endDate: '2013-02-04',
    happiness: 70,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_LES_MAINS_EN_PLUS: {
    title: 'Mailing papier Les Mains en Plus',
    subtitle: `Développement d'un mailing papier pour la société Les Mains en Plus.`,
    startDate: '2013-01-25',
    endDate: '2013-01-29',
    happiness: 30,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_LORIENTAL: {
    title: 'Mailing papier Loriental',
    subtitle: `Développement d'un mailing papier pour la société Loriental.`,
    startDate: '2013-01-20',
    endDate: '2013-01-24',
    happiness: 45,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_MEDIUM_MUSIQUE: {
    title: 'Mailing papier Medium Musique',
    subtitle: `Développement d'un mailing papier pour la société Medium Musique.`,
    startDate: '2013-01-15',
    endDate: '2013-01-19',
    happiness: 30,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_PACEO: {
    title: 'Mailing papier Paceo',
    subtitle: `Développement d'un mailing papier pour la société Paceo.`,
    startDate: '2013-01-10',
    endDate: '2013-01-14',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_SASSI: {
    title: 'Mailing papier Sassi',
    subtitle: `Développement d'un mailing papier pour la société Sassi.`,
    startDate: '2013-01-05',
    endDate: '2013-01-09',
    happiness: 10,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_SENLISS: {
    title: 'Mailing papier Senliss',
    subtitle: `Développement d'un mailing papier pour la société Senliss.`,
    startDate: '2013-01-01',
    endDate: '2013-01-04',
    happiness: 40,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_SPM: {
    title: 'Mailing papier SPM',
    subtitle: `Développement d'un mailing papier pour la société SPM.`,
    startDate: '2012-12-20',
    endDate: '2012-12-31',
    happiness: 15,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_STORES_ROBERT: {
    title: 'Mailing papier Stores Robert',
    subtitle: `Développement d'un mailing papier pour la société Stores Robert.`,
    startDate: '2012-12-15',
    endDate: '2012-12-19',
    happiness: 20,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_VERSAUD: {
    title: 'Mailing papier Versaud',
    subtitle: `Développement d'un mailing papier pour la société Versaud.`,
    startDate: '2012-12-10',
    endDate: '2012-12-14',
    happiness: 30,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
  SOLOCAL_M_VITEL_SPA: {
    title: 'Mailing papier Vitel Spa',
    subtitle: `Développement d'un mailing papier pour la société Vitel Spa.`,
    startDate: '2012-12-05',
    endDate: '2012-12-09',
    happiness: 70,
    category: [WORK_CATEGORY.MAILING],
    skills: SOLOCAL_MAILING_SKILLS,
  },
}
