import {SKILL_CATEGORY, SKILL_TITLE} from "../enums/data.enum";
import {SkillDataInterface} from "../interfaces/data.interface";

/**
 * Skills data
 */
export const DATA_SKILLS: SkillDataInterface[] = [
  {
    title: SKILL_TITLE.HTML,
    level: 100,
    color: '#E34C26',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 70,
    experience: 100,
    icon: 'html',
  },
  {
    title: SKILL_TITLE.CSS,
    level: 100,
    color: '#1572B6',
    category: [
      SKILL_CATEGORY.FRONT_END,
      SKILL_CATEGORY.CODE_LANGUAGE,
      SKILL_CATEGORY.DESIGN,
      SKILL_CATEGORY.STACK
    ],
    happiness: 80,
    experience: 100,
    icon: 'css',
  },
  {
    title: SKILL_TITLE.SCSS,
    level: 100,
    color: '#CC6699',
    category: [
      SKILL_CATEGORY.FRONT_END,
      SKILL_CATEGORY.CODE_LANGUAGE,
      SKILL_CATEGORY.DESIGN,
      SKILL_CATEGORY.STACK
    ],
    happiness: 100,
    experience: 100,
    favorite: true,
    icon: 'scss',
  },
  {
    title: SKILL_TITLE.DART_SASS,
    level: 100,
    color: '#CC6699',
    category: [
      SKILL_CATEGORY.FRONT_END,
      SKILL_CATEGORY.CODE_LANGUAGE,
      SKILL_CATEGORY.DESIGN,
      SKILL_CATEGORY.STACK
    ],
    happiness: 100,
    experience: 100,
    icon: 'scss',
  },
  {
    title: SKILL_TITLE.LESS,
    level: 90,
    color: '#1D365D',
    category: [
      SKILL_CATEGORY.FRONT_END,
      SKILL_CATEGORY.CODE_LANGUAGE,
      SKILL_CATEGORY.DESIGN,
      SKILL_CATEGORY.STACK
    ],
    happiness: 80,
    experience: 20,
    icon: 'less',
  },
  {
    title: SKILL_TITLE.JAVASCRIPT,
    level: 100,
    color: '#F7DF1E',
    category: [
      SKILL_CATEGORY.FRONT_END,
      SKILL_CATEGORY.BACK_END,
      SKILL_CATEGORY.CODE_LANGUAGE,
      SKILL_CATEGORY.STACK
    ],
    happiness: 100,
    experience: 100,
    favorite: true,
    icon: 'javascript',
  },
  {
    title: SKILL_TITLE.NODE_JS,
    level: 96,
    color: '#339933',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 100,
    experience: 92,
    favorite: true,
    icon: 'node-js',
  },
  {
    title: SKILL_TITLE.TYPESCRIPT,
    level: 98,
    color: '#007ACC',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 100,
    experience: 80,
    favorite: true,
    icon: 'typescript',
  },
  {
    title: SKILL_TITLE.ANGULAR,
    level: 100,
    color: '#DD0031',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 100,
    experience: 92,
    favorite: true,
    icon: 'angular',
  },
  {
    title: SKILL_TITLE.REACT,
    level: 35,
    color: '#61DAFB',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY, SKILL_CATEGORY.STACK],
    happiness: 92,
    experience: 10,
    icon: 'react',
  },
  {
    title: SKILL_TITLE.VUE,
    level: 20,
    color: '#4FC08D',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 60,
    experience: 10,
    icon: 'vue',
  },
  {
    title: SKILL_TITLE.SYMFONY,
    level: 60,
    color: '#40ba2f',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 60,
    experience: 40,
    icon: 'symfony',
  },
  {
    title: SKILL_TITLE.ZEND,
    level: 33,
    color: '#40ba2f',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 15,
    experience: 40,
    icon: 'zend',
  },
  {
    title: SKILL_TITLE.LARAVEL,
    color: '#FF2D20',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    icon: 'laravel',
  },
  {
    title: SKILL_TITLE.PHP,
    level: 96,
    color: '#777BB4',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 45,
    experience: 100,
    icon: 'php',
  },
  {
    title: SKILL_TITLE.JAVA,
    color: '#007396',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    icon: 'java',
  },
  {
    title: SKILL_TITLE.C_SHARP,
    color: '#239120',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    icon: 'c-sharp',
  },
  {
    title: SKILL_TITLE.C_PLUS_PLUS,
    color: '#00599C',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    icon: 'c++',
  },
  {
    title: SKILL_TITLE.C,
    color: '#A8B9CC',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    icon: 'c',
  },
  {
    level: 20,
    title: SKILL_TITLE.PYTHON,
    color: '#3776AB',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 45,
    experience: 10,
    icon: 'python',
  },
  {
    title: SKILL_TITLE.TWIG,
    level: 94,
    color: '#40ba2f',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE, SKILL_CATEGORY.STACK],
    happiness: 90,
    favorite: true,
    icon: 'symfony',
  },
  {
    title: SKILL_TITLE.MONGODB,
    level: 73,
    color: '#47A248',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE,SKILL_CATEGORY.STACK],
    happiness: 80,
    icon: 'mongodb',
  },
  {
    title: SKILL_TITLE.MYSQL,
    level: 88,
    color: '#4479A1',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE, SKILL_CATEGORY.STACK],
    happiness: 65,
    icon: 'mysql',
  },
  {
    title: SKILL_TITLE.POSTGRESQL,
    level: 65,
    color: '#336791',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE, SKILL_CATEGORY.STACK],
    happiness: 75,
    icon: 'postgresql',
  },
  {
    title: SKILL_TITLE.REDIS,
    color: '#DC382D',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE, SKILL_CATEGORY.STACK],
    icon: 'redis',
  },
  {
    title: SKILL_TITLE.GIT,
    level: 93,
    color: '#F05032',
    category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.OTHERS],
    happiness: 95,
    experience: 100,
    favorite: true,
    icon: 'git',
  },
  {
    title: SKILL_TITLE.WEBPACK,
    level: 85,
    color: '#8DD6F9',
    category: [SKILL_CATEGORY.DEVOPS],
    happiness: 85,
    experience: 70,
    icon: 'webpack',
  },
  {
    title: SKILL_TITLE.GULP,
    level: 95,
    color: '#CF4647',
    category: [SKILL_CATEGORY.DEVOPS],
    happiness: 80,
    experience: 80,
    icon: 'gulp',
  },
  {
    title: SKILL_TITLE.BOOTSTRAP,
    level: 70,
    color: '#563D7C',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 45,
    experience: 30,
    icon: 'bootstrap',
  },
  {
    title: SKILL_TITLE.FOUNDATION,
    level: 92,
    color: '#7768AE',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 30,
    experience: 90,
    icon: 'foundation',
  },
  {
    title: SKILL_TITLE.ANGULAR_MATERIAL,
    level: 95,
    color: '#0081CB',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 96,
    experience: 80,
    favorite: true,
    icon: 'angular',
  },
  {
    title: SKILL_TITLE.MATERIAL_UI,
    level: 79,
    color: '#0081CB',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 70,
    experience: 40,
    icon: 'material-ui',
  },
  {
    title: SKILL_TITLE.BULMA,
    color: '#00D1B2',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    icon: 'bulma',

  },
  {
    title: SKILL_TITLE.TAILWIND_CSS,
    level: 30,
    color: '#38B2AC',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 75,
    experience: 10,
    icon: 'tailwind-css',
  },
  {
    title: SKILL_TITLE.JQUERY,
    level: 100,
    color: '#0769AD',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY, SKILL_CATEGORY.STACK],
    happiness: 68,
    experience: 100,
    icon: 'jquery',
  },
  {
    title: SKILL_TITLE.RXJS,
    level: 80,
    color: '#B7178C',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY, SKILL_CATEGORY.STACK],
    happiness: 100,
    experience: 70,
    icon: 'rxjs',
  },
  {
    title: SKILL_TITLE.NESTJS,
    level: 90,
    color: '#E0234E',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 90,
    experience: 60,
    icon: 'nestjs',
  },
  {
    title: SKILL_TITLE.EXPRESS,
    level: 80,
    color: '#73b22a',
    category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK, SKILL_CATEGORY.STACK],
    happiness: 85,
    experience: 40,
    icon: 'node-js',
  },
  {
    title: SKILL_TITLE.JEST,
    level: 50,
    color: '#C21325',
    category: [SKILL_CATEGORY.E2E],
    happiness: 60,
    experience: 5,
    icon: 'jest',
  },
  {
    title: SKILL_TITLE.MOCHA,
    color: '#8D6748',
    category: [SKILL_CATEGORY.E2E],
    icon: 'mocha',
  },
  {
    title: SKILL_TITLE.CYPRUS,
    color: '#17202C',
    category: [SKILL_CATEGORY.E2E],
    icon: 'cyprus',
  },
  {
    title: SKILL_TITLE.JASMINE,
    color: '#8A4182',
    category: [SKILL_CATEGORY.E2E],
    icon: 'jasmine',
  },
  {
    title: SKILL_TITLE.KARMA,
    level: 40,
    color: '#C32F27',
    category: [SKILL_CATEGORY.E2E],
    happiness: 40,
    experience: 5,
    icon: 'karma',
  },
  {
    title: SKILL_TITLE.PROTRACTOR,
    color: '#E1583E',
    category: [SKILL_CATEGORY.E2E],
    icon: 'protractor',
  },
  {
    title: SKILL_TITLE.STORYBOOK,
    level: 94,
    color: '#FF4785',
    category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.OTHERS],
    happiness: 95,
    experience: 60,
    favorite: true,
    icon: 'storybook',
  },
  {
    title: SKILL_TITLE.DOCKER,
    level: 65,
    color: '#2496ED',
    category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.OTHERS],
    happiness: 60,
    experience: 60,
    icon: 'docker',
  },
  {
    title: SKILL_TITLE.NGINX,
    level: 30,
    color: '#009639',
    category: [SKILL_CATEGORY.DEVOPS],
    happiness: 45,
    experience: 10,
    icon: 'nginx',
  },
  {
    title: SKILL_TITLE.APACHE,
    level: 10,
    color: '#D22128',
    category: [SKILL_CATEGORY.DEVOPS],
    icon: 'apache',
  },
  {
    title: SKILL_TITLE.AWS,
    level: 20,
    color: '#232F3E',
    category: [SKILL_CATEGORY.DEVOPS],
    happiness: 20,
    experience: 10,
    icon: 'aws',
  },
  {
    title: SKILL_TITLE.GITHUB,
    level: 100,
    color: '#181717',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 95,
    experience: 100,
    icon: 'github',
  },
  {
    title: SKILL_TITLE.GITLAB,
    level: 100,
    color: '#FCA121',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 94,
    experience: 100,
    icon: 'gitlab',
  },
  {
    title: SKILL_TITLE.JENKINS,
    level: 60,
    color: '#D24939',
    category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.TOOL],
    happiness: 50,
    experience: 80,
    icon: 'jenkins',
  },
  {
    title: SKILL_TITLE.SONARQUBE,
    level: 35,
    color: '#4E9BCD',
    category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.TOOL],
    happiness: 50,
    experience: 40,
    icon: 'sonarqube',
  },
  {
    title: SKILL_TITLE.BITBUCKET,
    color: '#205081',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    icon: 'bitbucket',
  },
  {
    title: SKILL_TITLE.JIRA,
    color: '#0052CC',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    icon: 'jira',
  },
  {
    title: SKILL_TITLE.CONFLUENCE,
    color: '#172B4D',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    icon: 'confluence',
  },
  {
    title: SKILL_TITLE.POSTMAN,
    level: 85,
    color: '#FF6C37',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 90,
    experience: 80,
    icon: 'postman',
  },
  {
    title: SKILL_TITLE.BASH,
    level: 20,
    color: '#4EAA25',
    category: [SKILL_CATEGORY.DEVOPS],
    icon: 'bash',
  },
  {
    title: SKILL_TITLE.LINUX,
    level: 80,
    color: '#FCC624',
    category: [SKILL_CATEGORY.OS],
    happiness: 60,
    experience: 30,
    icon: 'linux',
  },
  {
    title: SKILL_TITLE.WINDOWS,
    level: 100,
    color: '#0078D6',
    category: [SKILL_CATEGORY.OS],
    happiness: 90,
    experience: 100,
    icon: 'windows',
  },

  {
    title: SKILL_TITLE.MAC_OS,
    level: 90,
    color: '#999999',
    category: [SKILL_CATEGORY.OS],
    happiness: 95,
    experience: 90,
    favorite: true,
    icon: 'mac-os',
  },
  {
    title: SKILL_TITLE.FLASH,
    level: 85,
    color: '#FF0000',
    category: [SKILL_CATEGORY.APPLICATION],
    happiness: 65,
    experience: 70,
    icon: 'flash',
  },
  {
    title: SKILL_TITLE.TOON_BOOM_HARMONY,
    level: 90,
    color: '#bc5e66',
    category: [SKILL_CATEGORY.APPLICATION],
    happiness: 75,
    experience: 80,
    icon: 'toon-boom-harmony',
  },
  {
    title: SKILL_TITLE.MAYA3D,
    level: 70,
    color: '#0696D7',
    category: [SKILL_CATEGORY.APPLICATION],
    happiness: 65,
    experience: 70,
    icon: 'maya3d',
  },
  {
    title: SKILL_TITLE.BLENDER,
    level: 50,
    color: '#F5792A',
    category: [SKILL_CATEGORY.APPLICATION],
    happiness: 40,
    experience: 20,
    icon: 'blender',
  },
  {
    title: SKILL_TITLE.PHOTOSHOP,
    level: 100,
    color: '#31A8FF',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    happiness: 85,
    experience: 100,
    icon: 'photoshop',
  },
  {
    title: SKILL_TITLE.ILLUSTRATOR,
    level: 90,
    color: '#FF9A00',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    happiness: 80,
    experience: 90,
    icon: 'illustrator',
  },
  {
    title: SKILL_TITLE.FIGMA,
    color: '#F24E1E',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    icon: 'figma',
  },
  {
    title: SKILL_TITLE.XD,
    color: '#FF61F6',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    icon: 'xd',
  },
  {
    title: SKILL_TITLE.PREMIERE_PRO,
    level: 100,
    color: '#100d6a',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    happiness: 85,
    experience: 80,
    icon: 'premiere-pro',
  },
  {
    title: SKILL_TITLE.AFTER_EFFECTS,
    level: 90,
    color: '#100d6a',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    happiness: 85,
    experience: 80,
    icon: 'after-effects',
  },
  {
    title: SKILL_TITLE.INDESIGN,
    level: 90,
    color: '#820821',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.DESIGN
    ],
    happiness: 75,
    experience: 80,
    icon: 'indesign',
  },
  {
    title: SKILL_TITLE.CUBASE,
    level: 100,
    color: '#970d0d',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.MUSIC
    ],
    happiness: 90,
    experience: 80,
    icon: 'cubase',
  },
  {
    title: SKILL_TITLE.REAPER,
    level: 80,
    color: '#19da8a',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.MUSIC
    ],
    happiness: 70,
    experience: 60,
    icon: 'mix',
  },
  {
    title: SKILL_TITLE.PRO_TOOLS,
    level: 70,
    color: '#6018bc',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.MUSIC
    ],
    happiness: 60,
    experience: 40,
    icon: 'pro-tools',
  },
  {
    title: SKILL_TITLE.ABLETON_LIVE,
    level: 65,
    color: '#000000',
    category: [
      SKILL_CATEGORY.APPLICATION,
      SKILL_CATEGORY.MUSIC
    ],
    happiness: 70,
    experience: 80,
    icon: 'ableton-live',
  },
  {
    title: SKILL_TITLE.WORDPRESS,
    level: 100,
    color: '#21759B',
    category: [SKILL_CATEGORY.CMS],
    happiness: 92,
    experience: 100,
    favorite: true,
    icon: 'wordpress',
  },
  {
    title: SKILL_TITLE.JOOMLA,
    level: 45,
    color: '#5091CD',
    category: [SKILL_CATEGORY.CMS],
    happiness: 50,
    experience: 10,
    icon: 'joomla',
  },
  {
    title: SKILL_TITLE.DRUPAL,
    level: 80,
    color: '#0C76AB',
    category: [SKILL_CATEGORY.CMS],
    happiness: 30,
    experience: 20,
    icon: 'drupal',
  },
  {
    title: SKILL_TITLE.MAGENTO,
    color: '#F26322',
    category: [SKILL_CATEGORY.CMS],
    icon: 'magento',
  },
  {
    title: SKILL_TITLE.SHOPIFY,
    color: '#96BF48',
    category: [SKILL_CATEGORY.CMS],
    icon: 'shopify',
  },
  {
    title: SKILL_TITLE.WOOCOMMERCE,
    level: 100,
    color: '#96588A',
    category: [SKILL_CATEGORY.CMS],
    happiness: 90,
    experience: 100,
    icon: 'woocommerce',
  },
  {
    title: SKILL_TITLE.PRESTASHOP,
    level: 25,
    color: '#F05A22',
    category: [SKILL_CATEGORY.CMS],
    icon: 'prestashop',
  },
  {
    title: SKILL_TITLE.OPEN_CART,
    color: '#E67E22',
    category: [SKILL_CATEGORY.CMS],
    icon: 'open-cart',
  },
  {
    title: SKILL_TITLE.WEBSTORM,
    level: 100,
    color: '#58e6cc',
    category: [SKILL_CATEGORY.IDE],
    happiness: 94,
    experience: 85,
    favorite: true,
    icon: 'webstorm',
  },
  {
    title: SKILL_TITLE.VISUAL_STUDIO_CODE,
    level: 100,
    color: '#007ACC',
    category: [SKILL_CATEGORY.IDE],
    happiness: 80,
    experience: 95,
    icon: 'visual-studio-code',
  },
  {
    title: SKILL_TITLE.SUBLIME_TEXT,
    level: 100,
    color: '#FF9800',
    category: [SKILL_CATEGORY.IDE],
    happiness: 60,
    experience: 95,
    icon: 'sublime-text',
  },
  {
    title: SKILL_TITLE.ATOM,
    level: 70,
    color: '#66595C',
    category: [SKILL_CATEGORY.IDE],
    happiness: 50,
    experience: 20,
    icon: 'atom',
  },
  {
    title: SKILL_TITLE.BRACKETS,
    level: 100,
    color: '#F27405',
    category: [SKILL_CATEGORY.IDE],
    happiness: 50,
    experience: 100,
    icon: 'brackets',
  },
  {
    title: SKILL_TITLE.PHP_STORM,
    level: 100,
    color: '#9b09e5',
    category: [SKILL_CATEGORY.IDE],
    happiness: 90,
    experience: 80,
    icon: 'php-storm',
  },
  {
    title: SKILL_TITLE.XCODE,
    level: 60,
    color: '#1575F9',
    category: [SKILL_CATEGORY.IDE],
    happiness: 80,
    experience: 30,
    icon: 'xcode',
  },
  {
    title: SKILL_TITLE.TRELLO,
    level: 90,
    color: '#0079BF',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 70,
    experience: 100,
    icon: 'trello'
  },
  {
    title: SKILL_TITLE.CLICK_UP,
    level: 100,
    color: '#7AC943',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 85,
    experience: 100,
    icon: 'click-up'
  },
  {
    title: SKILL_TITLE.WRIKE,
    level: 95,
    color: '#00AEEF',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 60,
    experience: 80,
    icon: 'wrike'
  },
  {
    title: SKILL_TITLE.SLACK,
    level: 70,
    color: '#4A154B',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 70,
    experience: 80,
    icon: 'slack'
  },
  {
    title: SKILL_TITLE.DISCORD,
    level: 100,
    color: '#7289DA',
    category: [SKILL_CATEGORY.OTHERS, SKILL_CATEGORY.TOOL],
    happiness: 95,
    experience: 100,
    icon: 'discord'
  },
  {
    title: SKILL_TITLE.TECHNICAL_ENGLISH,
    level: 100,
    color: '#F5F5F5',
    category: [SKILL_CATEGORY.OTHERS],
    happiness: 95,
    experience: 100,
    icon: 'english'
  },
  {
    title: SKILL_TITLE.FRENCH,
    level: 100,
    color: '#F5F5F5',
    category: [SKILL_CATEGORY.OTHERS],
    happiness: 95,
    experience: 100,
    icon: 'french'
  },
  {
    title: SKILL_TITLE.AGILE,
    level: 80,
    color: '#F5F5F5',
    category: [SKILL_CATEGORY.OTHERS],
    happiness: 95,
    experience: 75,
    icon: 'agile'
  },
  {
    title: SKILL_TITLE.MASTERING,
    level: 85,
    color: '#e84910',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 70,
    icon: 'mao',
  },
  {
    title: SKILL_TITLE.MIXING,
    level: 90,
    color: '#e89c10',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 80,
    icon: 'mao',
  },
  {
    title: SKILL_TITLE.RECORDING,
    level: 95,
    color: '#e8e310',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 80,
    icon: 'recording',
  },
  {
    title: SKILL_TITLE.MUSIC_THEORY,
    level: 100,
    color: '#10e8e3',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 100,
    icon: 'composition',
  },
  {
    title: SKILL_TITLE.MAO,
    level: 80,
    color: '#e81010',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 70,
    icon: 'mao',
  },
  {
    title: SKILL_TITLE.COMPOSITION,
    level: 85,
    color: '#10e8e3',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 90,
    experience: 70,
    icon: 'composition',
  },
  {
    title: SKILL_TITLE.VIOLIN,
    level: 95,
    color: '#e8e310',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 95,
    experience: 100,
    icon: 'violin',
  },
  {
    title: SKILL_TITLE.PIANO,
    level: 40,
    color: '#e8e310',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 80,
    experience: 60,
    icon: 'piano',
  },
  {
    title: SKILL_TITLE.GUITAR,
    level: 30,
    color: '#e8e310',
    category: [SKILL_CATEGORY.MUSIC],
    happiness: 70,
    experience: 20,
    icon: 'guitar',
  }
];
