import {SKILL_CATEGORY} from "../enums/data.enum";

export const MainData = {
  /**
   * Skills
   */
  SKILLS: [
    {
      title: 'HTML',
      level: 100,
      color: '#E34C26',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 70,
      experience: 100,
    },
    {
      title: 'CSS',
      level: 100,
      color: '#1572B6',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 80,
      experience: 100,
    },
    {
      title: 'SCSS',
      level: 100,
      color: '#CC6699',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 95,
      experience: 100,
      favorite: true,
    },
    {
      title: 'Dart-SASS',
      level: 100,
      color: '#CC6699',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 100,
      experience: 100,
      favorite: true,
    },
    {
      title: 'Less',
      level: 90,
      color: '#1D365D',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 80,
      experience: 20,
    },
    {
      title: 'JavaScript',
      level: 100,
      color: '#F7DF1E',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 100,
      experience: 100,
      favorite: true,
    },
    {
      title: 'NodeJS',
      level: 100,
      color: '#339933',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 90,
      experience: 92,
      favorite: true,
    },
    {
      title: 'TypeScript',
      level: 95,
      color: '#007ACC',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 100,
      experience: 80,
      favorite: true,
    },
    {
      title: 'Angular',
      level: 100,
      color: '#DD0031',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 100,
      experience: 80,
      favorite: true,
    },
    {
      title: 'React',
      level: 15,
      color: '#61DAFB',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY],
      happiness: 95,
      experience: 10,
    },
    {
      title: 'VueJS',
      level: 20,
      color: '#4FC08D',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 60,
      experience: 10,
    },
    {
      title: 'Symfony',
      level: 60,
      color: '#40ba2f',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 60,
      experience: 40,
    },
    {
      title: 'PHP',
      level: 100,
      color: '#777BB4',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 50,
      experience: 100,
    },
    {
      title: 'Java',
      color: '#007396',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
    },
    {
      title: 'C#',
      color: '#239120',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
    },
    {
      title: 'C++',
      color: '#00599C',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
    },
    {
      title: 'C',
      color: '#A8B9CC',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
    },
    {
      title: 'Python',
      color: '#3776AB',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.CODE_LANGUAGE],
    },
    {
      title: 'Twig',
      level: 90,
      color: '#40ba2f',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.CODE_LANGUAGE],
      happiness: 100,
      favorite: true,
    },
    {
      title: 'MongoDB',
      level: 75,
      color: '#47A248',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE],
      happiness: 100,
    },
    {
      title: 'MySQL',
      level: 90,
      color: '#4479A1',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE],
      happiness: 70,
    },
    {
      title: 'PostgreSQL',
      level: 60,
      color: '#336791',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE],
      happiness: 60,
    },
    {
      title: 'Redis',
      color: '#DC382D',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.DATABASE],
    },
    {
      title: 'Git',
      level: 92,
      color: '#F05032',
      category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.OTHERS],
      happiness: 100,
      experience: 100,
      favorite: true,
    },
    {
      title: 'Webpack',
      level: 85,
      color: '#8DD6F9',
      category: [SKILL_CATEGORY.DEVOPS],
      happiness: 80,
      experience: 70,
    },
    {
      title: 'Gulp',
      level: 95,
      color: '#CF4647',
      category: [SKILL_CATEGORY.DEVOPS],
      happiness: 85,
      experience: 80,
    },
    {
      title: 'Bootstrap',
      level: 80,
      color: '#563D7C',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 45,
      experience: 30,
    },
    {
      title: 'Foundation',
      level: 95,
      color: '#7768AE',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 30,
      experience: 90,
    },
    {
      title: 'Angular Material',
      level: 95,
      color: '#0081CB',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 100,
      experience: 80,
      favorite: true,
    },
    {
      title: 'Bulma',
      color: '#00D1B2',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],

    },
    {
      title: 'Tailwind',
      level: 30,
      color: '#38B2AC',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 75,
      experience: 10,
    },
    {
      title: 'jQuery',
      level: 100,
      color: '#0769AD',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY],
      happiness: 80,
      experience: 100,
    },
    {
      title: 'RxJS',
      level: 80,
      color: '#B7178C',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.LIBRARY],
      happiness: 100,
      experience: 70,
    },
    {
      title: 'NestJS',
      level: 90,
      color: '#E0234E',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 90,
      experience: 60,
    },
    {
      title: 'Express',
      level: 80,
      color: '#73b22a',
      category: [SKILL_CATEGORY.BACK_END, SKILL_CATEGORY.FRAMEWORK],
      happiness: 85,
      experience: 40,
    },
    {
      title: 'Jest',
      level: 50,
      color: '#C21325',
      category: [SKILL_CATEGORY.E2E],
      happiness: 60,
      experience: 5,
    },
    {
      title: 'Mocha',
      color: '#8D6748',
      category: [SKILL_CATEGORY.E2E],
    },
    {
      title: 'Chai',
      color: '#E0A428',
      category: [SKILL_CATEGORY.E2E],
    },
    {
      title: 'Cypress',
      color: '#17202C',
      category: [SKILL_CATEGORY.E2E],
    },
    {
      title: 'Jasmine',
      color: '#8A4182',
      category: [SKILL_CATEGORY.E2E],
    },
    {
      title: 'Karma',
      level: 40,
      color: '#C32F27',
      category: [SKILL_CATEGORY.E2E],
      happiness: 40,
      experience: 5,
    },
    {
      title: 'Protractor',
      color: '#E1583E',
      category: [SKILL_CATEGORY.E2E],
    },
    {
      title: 'Storybook',
      level: 90,
      color: '#FF4785',
      category: [SKILL_CATEGORY.FRONT_END, SKILL_CATEGORY.OTHERS],
      happiness: 100,
      experience: 60,
      favorite: true,
    },
    {
      title: 'Docker',
      level: 65,
      color: '#2496ED',
      category: [SKILL_CATEGORY.DEVOPS, SKILL_CATEGORY.OTHERS],
      happiness: 50,
      experience: 60,
    },
    {
      title: 'Nginx',
      level: 30,
      color: '#009639',
      category: [SKILL_CATEGORY.DEVOPS],
      happiness: 50,
      experience: 10,
    },
    {
      title: 'Apache',
      level: 10,
      color: '#D22128',
      category: [SKILL_CATEGORY.DEVOPS],
    },
    {
      title: 'Bash',
      level: 20,
      color: '#4EAA25',
      category: [SKILL_CATEGORY.DEVOPS],
    },
    {
      title: 'Linux',
      level: 80,
      color: '#FCC624',
      category: [SKILL_CATEGORY.OS],
      happiness: 60,
      experience: 30,
    },
    {
      title: 'Windows',
      level: 100,
      color: '#0078D6',
      category: [SKILL_CATEGORY.OS],
      happiness: 90,
      experience: 100,
    },

    {
      title: 'MacOS',
      level: 90,
      color: '#999999',
      category: [SKILL_CATEGORY.OS],
      happiness: 100,
      experience: 90,
      favorite: true,
    },
    {
      title: 'Photoshop',
      level: 100,
      color: '#31A8FF',
      category: [SKILL_CATEGORY.APPLICATION],
      happiness: 100,
      experience: 100,
    },
    {
      title: 'Illustrator',
      level: 90,
      color: '#FF9A00',
      category: [SKILL_CATEGORY.APPLICATION],
      happiness: 100,
      experience: 90,
    },
    {
      title: 'Figma',
      color: '#F24E1E',
      category: [SKILL_CATEGORY.APPLICATION],
    },
    {
      title: 'Adobe XD',
      color: '#FF61F6',
      category: [SKILL_CATEGORY.APPLICATION],
    },
    {
      title: 'Zeplin',
      color: '#323232',
      category: [SKILL_CATEGORY.APPLICATION],
    },
    {
      title: 'Adobe Premiere',
      level: 100,
      color: '#100d6a',
      category: [SKILL_CATEGORY.APPLICATION],
      happiness: 90,
      experience: 80,
    },
    {
      title: 'Adobe After Effects',
      level: 90,
      color: '#100d6a',
      category: [SKILL_CATEGORY.APPLICATION],
      happiness: 90,
      experience: 80,
    },
    {
      title: 'Adobe InDesign',
      level: 90,
      color: '#820821',
      category: [SKILL_CATEGORY.APPLICATION],
      happiness: 90,
      experience: 80,
    },
    {
      title: 'WordPress',
      level: 100,
      color: '#21759B',
      category: [SKILL_CATEGORY.CMS],
      happiness: 100,
      experience: 100,
      favorite: true,
    },
    {
      title: 'Joomla',
      level: 45,
      color: '#5091CD',
      category: [SKILL_CATEGORY.CMS],
      happiness: 50,
      experience: 10,
    },
    {
      title: 'Drupal',
      level: 80,
      color: '#0C76AB',
      category: [SKILL_CATEGORY.CMS],
      happiness: 30,
      experience: 20,
    },
    {
      title: 'Magento',
      color: '#F26322',
      category: [SKILL_CATEGORY.CMS],
    },
    {
      title: 'Shopify',
      color: '#96BF48',
      category: [SKILL_CATEGORY.CMS]
    },
    {
      title: 'WooCommerce',
      level: 100,
      color: '#96588A',
      category: [SKILL_CATEGORY.CMS],
      happiness: 100,
      experience: 100,
    },
    {
      title: 'PrestaShop',
      level: 25,
      color: '#F05A22',
      category: [SKILL_CATEGORY.CMS],
    },
    {
      title: 'OpenCart',
      color: '#E67E22',
      category: [SKILL_CATEGORY.CMS],
    },
    {
      title: 'Webstorm',
      level: 100,
      color: '#58e6cc',
      category: [SKILL_CATEGORY.IDE],
      happiness: 100,
      experience: 100,
      favorite: true,
    },
    {
      title: 'VS Code',
      level: 100,
      color: '#007ACC',
      category: [SKILL_CATEGORY.IDE],
      happiness: 92,
      experience: 100,
    },
    {
      title: 'Sublime Text',
      level: 100,
      color: '#FF9800',
      category: [SKILL_CATEGORY.IDE],
      happiness: 60,
      experience: 100,
    },
    {
      title: 'Atom',
      level: 70,
      color: '#66595C',
      category: [SKILL_CATEGORY.IDE],
      happiness: 50,
      experience: 20,
    },
    {
      title: 'Brackets',
      level: 100,
      color: '#F27405',
      category: [SKILL_CATEGORY.IDE],
      happiness: 50,
      experience: 100,
    },
    {
      title: 'PhpStorm',
      level: 100,
      color: '#9b09e5',
      category: [SKILL_CATEGORY.IDE],
      happiness: 90,
      experience: 80,
    },
  ],

  /**
   * Education
   */
  EDUCATION: [
    {
      title: 'Brevet des collèges',
      subtitle: 'Fin du collège',
      startDate: '2000-09-01',
      endDate: '2001-06-01',
      location: 'Lisieux, France',
      school: 'Lycée Frémont',
      happiness: 25,
    },
    {
      title: 'BEP M.I.G',
      subtitle: 'Métiers de l\'industrie graphique',
      startDate: '2001-09-01',
      endDate: '2003-06-01',
      location: 'Lisieux, France',
      school: 'Lycée Paul Cornu',
      happiness: 80,
    },
    {
      title: 'CAP D.E.C.G',
      subtitle: 'Dessin en communication et exécution graphique',
      startDate: '2003-09-01',
      endDate: '2005-06-01',
      location: 'Lisieux, France',
      school: 'Lycée Paul Cornu',
      happiness: 95,
    },
    {
      title: 'Arts Graphiques',
      subtitle: 'Arts Appliqués, Communication Visuelle, Design Graphique',
      startDate: '2005-09-01',
      endDate: '2007-06-01',
      location: 'Lisieux, France',
      school: 'Lycée Paul Cornu',
      happiness: 88,
    },
    {
      title: 'Animation 2D',
      subtitle: 'Animation 2D, Motion Design, Infographie',
      startDate: '2007-09-01',
      endDate: '2007-12-31',
      location: 'Angoulême, France',
      school: 'Éléphorm',
    },
    {
      title: 'Animation 3D',
      subtitle: 'Animation 3D, Motion Design, Infographie',
      startDate: '2008-01-01',
      endDate: '2008-06-01',
      location: 'Angoulême, France',
      school: 'EMCA',
    },
  ],

  /**
   * Work
   */
  WORK: [
    {
      title: 'Animateur 2D',
    }
  ],
}
